[project]
name = 'IoT-Device-Management-System'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.device-registration-contract]
path = 'contracts/device-registration-contract.clar'
clarity_version = 2
epoch = 2.5

[contracts.firmware-update-contract]
path = 'contracts/firmware-update-contract.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
